In [1]:
import numpy as np

In [5]:
np.eye(5, 5, 1) # последний параметр это сдвиг диагонали

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [79]:
a.max(axis=1) # вдоль строк забирает самые большие

array([  4, 200,  14, 100,  24])

In [80]:
a.mean(axis=None)

23.0

In [85]:
a

array([[  0,   1,   2,   3,   4],
       [  5, 200,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 100],
       [ 20,  21,  22,  23,  24]])

In [90]:
c = np.array(range(15, 40)).reshape(5, 5)

In [91]:
c

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [100]:
%%timeit
a.dot(c)

802 ns ± 8.71 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [101]:
%%timeit
a @ c

1.24 µs ± 4.98 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [105]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)

try:
    print(X @ Y.T)
    
except:
    print('matrix shapes do not match')


2 3
8 7 7 14 4 6


/tmp/ipykernel_6397/3043445894.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)


In [127]:
import pandas as pd
from urllib.request import urlopen
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')

In [128]:
f

In [129]:
from urllib.request import urlopen
import numpy as np

filename = input()
f = urlopen(filename)

https://stepic.org/media/attachments/lesson/16462/boston_houses.csv


In [130]:
f

In [131]:
df = np.loadtxt(f, skiprows=1, delimiter=",")

In [132]:
df.mean(axis=0)

array([22.53280632,  3.61352356, 11.36363636,  0.06916996,  0.55469506,
        6.28463439,  3.79504269])

In [136]:
X = np.array([[1, 60],[1, 50],[1, 75]])

In [137]:
X

array([[ 1, 60],
       [ 1, 50],
       [ 1, 75]])

In [138]:
Y = np.array([10, 7, 12]).reshape(3, 1)

In [139]:
Y

array([[10],
       [ 7],
       [12]])

In [141]:
Z = ((X.T).dot(X))

In [145]:

k = np.linalg.inv(Z).dot(X.T)

In [147]:
k.dot(Y)

array([[-2.34210526],
       [ 0.19473684]])

In [149]:
import urllib
from urllib import request
file = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
f = urllib.request.urlopen(file)



In [150]:
f

In [151]:
data = np.loadtxt(f, delimiter=',', skiprows=1)
data

array([[2.4000e+01, 6.3200e-03, 1.8000e+01, ..., 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [2.1600e+01, 2.7310e-02, 0.0000e+00, ..., 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [3.4700e+01, 2.7290e-02, 0.0000e+00, ..., 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [2.3900e+01, 6.0760e-02, 0.0000e+00, ..., 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [2.2000e+01, 1.0959e-01, 0.0000e+00, ..., 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [1.1900e+01, 4.7410e-02, 0.0000e+00, ..., 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [152]:
data.shape

(506, 7)

In [155]:
Y = data[..., 0] # первый столбец, то есть Y

In [184]:
G = data[..., 1:]

In [185]:
X = np.hstack((np.ones((506, 1)), G))

In [187]:
Q = np.linalg.inv((X.T @ X))

In [188]:
z = (Q @ X.T)@Y

In [191]:
print(*z)

-3.655804285058417 -0.2163955023691392 0.07373059817548971 4.412450576912836 -25.46844878410251 7.143201550745909 -1.3010876776491929


In [192]:
data

array([[2.4000e+01, 6.3200e-03, 1.8000e+01, ..., 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [2.1600e+01, 2.7310e-02, 0.0000e+00, ..., 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [3.4700e+01, 2.7290e-02, 0.0000e+00, ..., 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [2.3900e+01, 6.0760e-02, 0.0000e+00, ..., 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [2.2000e+01, 1.0959e-01, 0.0000e+00, ..., 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [1.1900e+01, 4.7410e-02, 0.0000e+00, ..., 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [194]:
data.shape

(506, 7)

In [20]:
import numpy as np

w = np.array([0, 0, 0]) # изначальные веса

examples = np.array([[1, 1, 0.3], [1, 0.4, 0.5], [1, 0.7, 0.8]])


def target(ex): # целевая
    if ex[0] == 1 and ex[1] == 1 and ex[2] == 0.3:
        return 1
    elif ex[0] == 1 and ex[1] == 0.4 and ex[2] == 0.5:
        return 1
    elif ex[0] == 1 and ex[1] == 0.7 and ex[2] == 0.8:
        return 0
    

def predict(ex): # предсказание
    summ = w.T @ ex
    print('Пример: ', ex)
    print('Сумматорная функция: ', summ)
    if summ > 0:
        return 1
    else:
        return 0
    

perfect = False # переменная отражает, что алгоритм будет работать до тех пор, пока все идеально не классифицируем
while not perfect:
    perfect = True # предполагаем, что уже идеально классифицируем примеры
    i = 0
    for e in examples:
        if predict(e) != target(e):
            perfect = False
            if predict(e) == 0:
                w = w + e
                print(f"{w} = {w} + {e} = {w + e}")
            elif predict(e) == 1:
                w = w - e
                print(f"{w} = {w} - {e} = {w - e}")
        i = i+1
        print(f'На шаге {i} получили w: ', w)
        print()
        print()
print('Итоговые веса:', w)


Пример:  [1.  1.  0.3]
Сумматорная функция:  0.0
Пример:  [1.  1.  0.3]
Сумматорная функция:  0.0
[1.  1.  0.3] = [1.  1.  0.3] + [1.  1.  0.3] = [2.  2.  0.6]
На шаге 1 получили w:  [1.  1.  0.3]


Пример:  [1.  0.4 0.5]
Сумматорная функция:  1.5499999999999998
На шаге 2 получили w:  [1.  1.  0.3]


Пример:  [1.  0.7 0.8]
Сумматорная функция:  1.94
Пример:  [1.  0.7 0.8]
Сумматорная функция:  1.94
Пример:  [1.  0.7 0.8]
Сумматорная функция:  1.94
[ 0.   0.3 -0.5] = [ 0.   0.3 -0.5] - [1.  0.7 0.8] = [-1.  -0.4 -1.3]
На шаге 3 получили w:  [ 0.   0.3 -0.5]


Пример:  [1.  1.  0.3]
Сумматорная функция:  0.15000000000000005
На шаге 1 получили w:  [ 0.   0.3 -0.5]


Пример:  [1.  0.4 0.5]
Сумматорная функция:  -0.12999999999999998
Пример:  [1.  0.4 0.5]
Сумматорная функция:  -0.12999999999999998
[1.  0.7 0. ] = [1.  0.7 0. ] + [1.  0.4 0.5] = [2.  1.1 0.5]
На шаге 2 получили w:  [1.  0.7 0. ]


Пример:  [1.  0.7 0.8]
Сумматорная функция:  1.49
Пример:  [1.  0.7 0.8]
Сумматорная функция:  